-- ====================================================================
-- Pending Jobs — Unique Active Job Per Reference
-- ====================================================================
-- This migration is no longer needed since payment processing jobs were
-- removed in the free MVP. The pending_jobs table was removed from the
-- initial schema. Kept as an empty migration for chronological integrity.